# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual trigger'
jobs:
  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        pythonVersion: [3.6, 3.7, 3.8, 3.9]
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.pythonVersion }}
    - name: Install dependencies
      run: |
        conda install jinja2
        conda install conda-build anaconda-client
    - name: Generate metadata for conda
      run: python meta.py
    - name: Build & Upload
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda config --set anaconda_upload yes
        conda build .
        
